# Generated by Django 5.0.4 on 2024-05-23 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="file_type",
            field=models.CharField(default="png", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="file",
            name="name",
            field=models.CharField(default="random.png", max_length=200),
            preserve_default=False,
        ),
    ]
