# Generated by Django 5.0.4 on 2024-06-22 10:43

import gdstorage.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_file_file_type_file_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(
                storage=gdstorage.storage.GoogleDriveStorage(), upload_to=""
            ),
        ),
    ]
